version: '3.8'

services:
  couchdb:
    image: couchdb:3.2
    container_name: couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin_password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - couchdb_network

volumes:
  couchdb_data:
    driver: local

networks:
  couchdb_network:
    driver: bridge

